#ifndef INCLUDED_ZENO_INTERACTION_CONSTRAINT_TYPES_HPP_
#define INCLUDED_ZENO_INTERACTION_CONSTRAINT_TYPES_HPP_

namespace ze {

	enum class ConstraintType {
		NONE = 0,
		X_POS,
		Y_POS,
		WIDTH,
		HEIGHT
	};

}

#endif // INCLUDED_ZENO_INTERACTION_CONSTRAINT_TYPES_HPP_