language: cpp

configuration:
    -   Debug

matrix:
  include:
  
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-8.0
          packages:
            - clang-8.0
      env: COMPILER='clang++-8.0'

install:
    -   git submodule update --init --recursive
    -   cmake --version
script:
    -   mkdir build
    -   cd build
    -   cmake ..
    -   cmake --build .
    -   ctest --no-label-summary --no-subproject-summary