dist: trusty
sudo: false
language: cpp

configuration:
    -   Debug

install:
  - if [ "$CXX" = "g++" ]; then export CXX="/usr/bin/clang++-5.0" CC="/usr/bin/clang-5.0"; fi
  - git submodule update --init --recursive
  - cmake --version

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0

script:
    -   mkdir build
    -   cd build
    -   cmake ..
    -   cmake --build .
    -   ctest --no-label-summary --no-subproject-summary
    -   cmake --install .