language: cpp
dist: bionic

matrix:
  include:

    - os: linux
      dist: bionic
      compiler: clang
      addons:
          apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-7
          packages:
            - clang-7


install:
    -   git submodule update --init --recursive
    -   cmake --version
    -   clang --version
script:
    -   mkdir build
    -   cd build
    -   cmake ..
    -   cmake --build .
    -   ctest --no-label-summary --no-subproject-summary