dist: xenial
sudo: false
language: cpp

configuration:
    -   Debug

install:
  - git submodule update --init --recursive
  - cmake --version
  
matrix:
  include:

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: llvm-toolchain-trusty-6.0
          packages: ['clang-6.0']
      env: COMPILER='clang++-6.0


script:
    -   mkdir build
    -   cd build
    -   cmake ..
    -   cmake --build .
    -   ctest --no-label-summary --no-subproject-summary