language: cpp
dist: trusty

matrix:
  include:

    - os: linux
      dist: xenial
      compiler: clang
      addons:
          apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
      env: TOOLSET=clang COMPILER=clang++-9 CXXSTD=c++17

install:
    -   git submodule update --init --recursive
    -   cmake --version
script:
    -   mkdir build
    -   cd build
    -   cmake ..
    -   cmake --build .
    -   ctest --no-label-summary --no-subproject-summary