language: cpp
dist: bionic
os: linux

jobs:
    include:
        -   os: windows
  
#    - os: linux
#      dist: bionic
#      addons:
#          apt:
#              sources:
#                - ubuntu-toolchain-r-test
#              packages:
#                - g++-7
#
#    - os: linux
#      dist: bionic
#      addons:
#          apt:
#              sources:
#                - ubuntu-toolchain-r-test
#                - llvm-toolchain-bionic-7
#              packages:
#                - clang-7
#
#    - os: osx
#      osx_image: xcode10
#      compiler: clang
#      env: 
#        - COMPILER=clang++
#        - CPP17=1




install:
    -   git submodule update --init --recursive
    -   cmake --version
    -   $CXX --version
    -   PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'

script:
    -   PowerShell -File ../scripts/windows_build.ps1
    

#script:
#    -   mkdir build
#    -   cd build
#       
#    -   echo "Generating Build Files"
#    -   echo cmake ..
#    -   cmake ..
#    
#    -   echo "Building Project"
#    -   echo cmake --build .
#    -   cmake --build .
#    
#    -   echo "Running Tests"
#    -   echo ctest --build-config $BUILD_TYPE --no-label-summary --no-subproject-summary --output-on-failure
#    -   ctest --build-config $BUILD_TYPE --no-label-summary --no-subproject-summary --output-on-failure
#
#    -   ls test
#    -   ls test/Debug
#    -   ls test/Release
#    -   ./test/Debug/ZenoTest.exe
#    -   ./test/Release/ZenoTest.exe
#    -   ls examples
#    -   ls examples/Debug
#    -   ls examples/Release
#    -   ./examples/Debug/ZenoMat4x4Printer.exe 1
#    -   ./examples/Release/ZenoMat4x4Printer.exe 1