language: cpp

jobs:
    include:
        -   os: windows
            env: BUILD_TYP=Debug

        -   os: windows
            env: BUILD_TYP=Release
  
        -   os: linux
            dist: bionic
            env: BUILD_TYP=Debug
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                    packages:
                        - g++-7

        -   os: linux
            dist: bionic
            env: BUILD_TYP=Release
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                    packages:
                        - g++-7
        
        -   os: linux
            dist: bionic
            env: BUILD_TYP=Debug
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                        - llvm-toolchain-bionic-7
                    packages:
                        - clang-7

        -   os: linux
            dist: bionic
            env: BUILD_TYP=Release
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                        - llvm-toolchain-bionic-7
                    packages:
                        - clang-7
        
        -   os: osx
            osx_image: xcode10
            env: BUILD_TYP=Debug
            compiler: clang
            env: 
                - COMPILER=clang++
                - CPP17=1

        -   os: osx
            osx_image: xcode10
            env: BUILD_TYP=Release
            compiler: clang
            env: 
                - COMPILER=clang++
                - CPP17=1




install:
    -   git submodule update --init --recursive
    -   cmake --version
    -   $CXX --version

script:
    -   mkdir build
    -   cd build

    -   cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
    -   cmake --build . --config $BUILD_TYPE
    -   ctest --build-config $BUILD_TYPE --output-on-failure --no-label-summary --no-subproject-summary --progress
