language: cpp

configuration:
    -   Debug
  
common_sources: &all_sources
  - ubuntu-toolchain-r-test
  - llvm-toolchain-xenial-6.0

matrix:
  include:
  
    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-6.0
            packages: 
            - 'clang-6.0'
      env: COMPILER='clang++-6.0'
      
install:
  - git submodule update --init --recursive
  - cmake --version

script:
    -   mkdir build
    -   cd build
    -   cmake ..
    -   cmake --build .
    -   ctest --no-label-summary --no-subproject-summary