language: cpp
dist: trusty

matrix:
  include:

    - os: linux
      dist: xenial
      compiler: clang
      addons:
          apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - libstdc++-8-dev
      env: COMPILER='clang++-6.0' CPP17=1

install:
    -   git submodule update --init --recursive
    -   cmake --version
script:
    -   mkdir build
    -   cd build
    -   cmake ..
    -   cmake --build .
    -   ctest --no-label-summary --no-subproject-summary