language: cpp

branches:
    except:
        -   appveyor-dev

jobs:
    include:  
        -   name: "OSX Clang Debug"
            os: osx
            osx_image: xcode10
            env: BUILD_TYPE=Debug
            compiler: clang
            env: 
                - COMPILER=clang++
                - CPP17=1

        -   name: "OSX Clang Release"
            os: osx
            osx_image: xcode10
            env: BUILD_TYPE=RelWithDebInfo
            compiler: clang
            env: 
                - COMPILER=clang++
                - CPP17=1

        -   name: "Linux G++ Debug"
            os: linux
            dist: bionic
            env: BUILD_TYPE=Debug
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                    packages:
                        - g++-7
                        - glew-utils
                        - libglew-dev
                        - libudev-dev
                        - libxrandr-dev
                        - libxinerama-dev
                        - libxcursor-dev
                        - libxi-dev
                        - libgl-dev
                        - libgl1-mesa-dev
                        - libglu1-mesa-dev
                        - libfreetype6-dev

        -   name: "Linux G++ Release"
            os: linux
            dist: bionic
            env: BUILD_TYPE=RelWithDebInfo
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                    packages:
                        - g++-7
                        - glew-utils
                        - libglew-dev
                        - libudev-dev
                        - libxrandr-dev
                        - libxinerama-dev
                        - libxcursor-dev
                        - libxi-dev
                        - libgl-dev
                        - libgl1-mesa-dev
                        - libglu1-mesa-dev
                        - libfreetype6-dev
        
        -   name: "Linux Clang Debug"
            os: linux
            dist: bionic
            env: BUILD_TYPE=Debug
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                        - llvm-toolchain-bionic-7
                    packages:
                        - clang-7
                        - glew-utils
                        - libglew-dev
                        - libudev-dev
                        - libxrandr-dev
                        - libxinerama-dev
                        - libxcursor-dev
                        - libxi-dev
                        - libgl-dev
                        - libgl1-mesa-dev
                        - libglu1-mesa-dev
                        - libfreetype6-dev

        -   name: "Linux Clang Release"
            os: linux
            dist: bionic
            env: BUILD_TYPE=RelWithDebInfo
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                        - llvm-toolchain-bionic-7
                    packages:
                        - clang-7
                        - glew-utils
                        - libglew-dev
                        - libudev-dev
                        - libxrandr-dev
                        - libxinerama-dev
                        - libxcursor-dev
                        - libxi-dev
                        - libgl-dev
                        - libgl1-mesa-dev
                        - libglu1-mesa-dev
                        - libfreetype6-dev
        
        -   name: "Windows Debug"
            os: windows
            env: BUILD_TYPE=Debug

        -   name: "Windows Release"
            os: windows
            env: BUILD_TYPE=RelWithDebInfo




install:
    -   git submodule update --init --recursive
    -   cmake --version
    -   $CXX --version

script:
    -   mkdir build
    -   cd build

    -   cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DGLEW_STATIC=ON ..
    -   cmake --build . --config $BUILD_TYPE
    -   if [ $BUILD_TYPE != "Debug" ]; then travis_terminate 0; fi
    -   ctest --build-config $BUILD_TYPE --output-on-failure --no-label-summary --no-subproject-summary --progress
