language: cpp
dist: bionic
os: linux

matrix:
  include:
  
#    - os: linux
#      dist: bionic
#      addons:
#          apt:
#              sources:
#                - ubuntu-toolchain-r-test
#              packages:
#                - g++-7
#
#    - os: linux
#      dist: bionic
#      addons:
#          apt:
#              sources:
#                - ubuntu-toolchain-r-test
#                - llvm-toolchain-bionic-7
#              packages:
#                - clang-7

    - os: osx
      dist: bionic
      addons:
          apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-7



install:
    -   git submodule update --init --recursive
    -   cmake --version

script:
    -   mkdir build
    -   cd build
    -   cmake ..
    -   cmake --build .
    -   ctest --no-label-summary --no-subproject-summary