language: cpp

jobs:
    include:
        -   name: "Windows Debug"
            os: windows
            env: BUILD_TYPE=Debug

        -   name: "Windows Release"
            os: windows
            env: BUILD_TYPE=Release
  
        -   name: "Linux G++ Debug"
            os: linux
            dist: bionic
            env: BUILD_TYPE=Debug
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                    packages:
                        - g++-7

        -   name: "Linux G++ Release"
            os: linux
            dist: bionic
            env: BUILD_TYPE=Release
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                    packages:
                        - g++-7
        
        -   name: "Linux Clang Debug"
            os: linux
            dist: bionic
            env: BUILD_TYPE=Debug
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                        - llvm-toolchain-bionic-7
                    packages:
                        - clang-7

        -   name: "Linux Clang Release"
            os: linux
            dist: bionic
            env: BUILD_TYPE=Release
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                        - llvm-toolchain-bionic-7
                    packages:
                        - clang-7
        
        -   name: "OSX Clang Debug"
            os: osx
            osx_image: xcode10
            env: BUILD_TYPE=Debug
            compiler: clang
            env: 
                - COMPILER=clang++
                - CPP17=1

        -   name: "OSX Clang Release"
            os: osx
            osx_image: xcode10
            env: BUILD_TYPE=Release
            compiler: clang
            env: 
                - COMPILER=clang++
                - CPP17=1




install:
    -   git submodule update --init --recursive
    -   cmake --version
    -   $CXX --version

script:
    -   mkdir build
    -   cd build

    -   cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
    -   cmake --build . --config $BUILD_TYPE
    -   ctest --build-config $BUILD_TYPE --output-on-failure --no-label-summary --no-subproject-summary --progress
