language: cpp
dist: bionic
os: linux
env: BUILD_TYPE=Debug

jobs:
    include:
        -   os: windows
            env: BUILD_TYPE=Debug

        -   os: windows
            env: BUILD_TYPE=Release
  
#    - os: linux
#      dist: bionic
#      addons:
#          apt:
#              sources:
#                - ubuntu-toolchain-r-test
#              packages:
#                - g++-7
#
#    - os: linux
#      dist: bionic
#      addons:
#          apt:
#              sources:
#                - ubuntu-toolchain-r-test
#                - llvm-toolchain-bionic-7
#              packages:
#                - clang-7
#
#    - os: osx
#      osx_image: xcode10
#      compiler: clang
#      env: 
#        - COMPILER=clang++
#        - CPP17=1




install:
    -   git submodule update --init --recursive
    -   cmake --version
    -   $CXX --version

script:
    -   echo $BUILD_TYPE
    -   mkdir build
    -   cd build
    -   echo cmake --config $BUILD_TYPE ..
    -   cmake --config $BUILD_TYPE ..
    -   echo cmake --build . --config $BUILD_TYPE
    -   cmake --build . --config $BUILD_TYPE
    -   echo ctest --build-config $BUILD_TYPE --no-label-summary --no-subproject-summary --output-on-failure
    -   ctest --build-config $BUILD_TYPE --no-label-summary --no-subproject-summary --output-on-failure