language: cpp

branches:
    except:
        -   appveyor-dev

jobs:
    include:  
        -   name: "OSX Clang Debug"
            os: osx
            osx_image: xcode10
            compiler: clang
            env: 
                - COMPILER=clang++
                - CPP17=1
                - BUILD_TYPE=Debug
                - OPERATINGSYSTEM=OSX

        -   name: "OSX Clang Release"
            os: osx
            osx_image: xcode10
            compiler: clang
            env: 
                - COMPILER=clang++
                - CPP17=1
                - BUILD_TYPE=RelWithDebInfo
                - OPERATINGSYSTEM=OSX

        -   name: "Linux G++ Debug"
            os: linux
            dist: bionic
            env: 
                - BUILD_TYPE=Debug
                - OPERATINGSYSTEM=LINUX
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                    packages:
                        - g++-7
                        - glew-utils
                        - libglew-dev
                        - libudev-dev
                        - libxrandr-dev
                        - libxinerama-dev
                        - libxcursor-dev
                        - libxi-dev
                        - libgl-dev
                        - libgl1-mesa-dev
                        - libglu1-mesa-dev
                        - libfreetype6-dev

        -   name: "Linux G++ Release"
            os: linux
            dist: bionic
            env: 
                - BUILD_TYPE=RelWithDebInfo
                - OPERATINGSYSTEM=LINUX
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                    packages:
                        - g++-7
                        - glew-utils
                        - libglew-dev
                        - libudev-dev
                        - libxrandr-dev
                        - libxinerama-dev
                        - libxcursor-dev
                        - libxi-dev
                        - libgl-dev
                        - libgl1-mesa-dev
                        - libglu1-mesa-dev
                        - libfreetype6-dev
        
        -   name: "Linux Clang Debug"
            os: linux
            dist: bionic
            env:
                - BUILD_TYPE=Debug
                - OPERATINGSYSTEM=LINUX
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                        - llvm-toolchain-bionic-7
                    packages:
                        - clang-7
                        - glew-utils
                        - libglew-dev
                        - libudev-dev
                        - libxrandr-dev
                        - libxinerama-dev
                        - libxcursor-dev
                        - libxi-dev
                        - libgl-dev
                        - libgl1-mesa-dev
                        - libglu1-mesa-dev
                        - libfreetype6-dev

        -   name: "Linux Clang Release"
            os: linux
            dist: bionic
            env: 
                - BUILD_TYPE=RelWithDebInfo
                - OPERATINGSYSTEM=LINUX
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                        - llvm-toolchain-bionic-7
                    packages:
                        - clang-7
                        - glew-utils
                        - libglew-dev
                        - libudev-dev
                        - libxrandr-dev
                        - libxinerama-dev
                        - libxcursor-dev
                        - libxi-dev
                        - libgl-dev
                        - libgl1-mesa-dev
                        - libglu1-mesa-dev
                        - libfreetype6-dev
        
        -   name: "Windows Debug"
            os: windows
            env: 
                - BUILD_TYPE=Debug
                - OPERATINGSYSTEM=WINDOWS
                - OPENALSOFT_ROOT="../../external/OpenAL"

        -   name: "Windows Release"
            os: windows
            env: 
                - BUILD_TYPE=RelWithDebInfo
                - OPERATINGSYSTEM=WINDOWS
                - OPENALSOFT_ROOT="../../external/OpenAL"




install:
    -   git submodule update --init --recursive
    -   cmake --version
    -   $CXX --version
    -   if [ $OPERATINGSYSTEM = "WINDOWS" ]; then .\scripts\download_extract_extern.ps1; fi

script:
    -   mkdir build
    -   cd build
    -   if ! cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DGLEW_STATIC=ON ..; then travis_terminate 1; fi 
    -   if ! cmake --build . --config $BUILD_TYPE; then travis_terminate 1; fi 
    -   if [ $BUILD_TYPE != "Debug" ]; then travis_terminate 0; fi
    -   ctest --build-config $BUILD_TYPE --output-on-failure --no-label-summary --no-subproject-summary --progress
