image:
 - Visual Studio 2019
 #- Visual Studio 2017

platform:
 - Win32
 #-	x64

configuration:
 - Debug
 # - Release

init:
 - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019" )
 - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017" )

build:
  - mkdir build
  - cd build
  - echo {CONFIGURATION}
  - echo %generator%
  - cmake -G %generator% -DCMAKE_BUILD_TYPE={CONFIGURATION} ..
  - cmake --build . --config {CONFIGURATION}
  - ctest --build-config {CONFIGURATION} --output-on-failure --no-label-summary --no-subproject-summary --progress
