branches:
 except:
  - travis-dev

image:
 - Visual Studio 2019
 - Visual Studio 2017

platform:
 - Win32
 - x64

configuration:
 - Debug
 - Release

init:
 - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019" )
 - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017" )

install:
- cmd: |-
    git submodule update --init --recursive

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake -G %generator% -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DGLEW_STATIC=ON ..

build_script:
- cmd: |-
    cmake --build . --config %CONFIGURATION%

test_script:
- cmd: |-
    ctest --build-config %CONFIGURATION% --output-on-failure --no-label-summary --no-subproject-summary --progress
