#ifndef INCLUDED_ZENO_INTERACTION_TRANSITIONS_TRANSITION_TYPES_HPP_
#define INCLUDED_ZENO_INTERACTION_TRANSITIONS_TRANSITION_TYPES_HPP_

namespace ze {

	enum class TransitionTypes {
		X_POS,
		Y_POS,
		WIDTH,
		HEIGHT,
		ALPHA
	};

}

#endif // INCLUDED_ZENO_INTERACTION_TRANSITIONS_TRANSITION_TYPES_HPP_